config/routes.rb
Rails.application.routes.draw do
  root "public/homes#top"
  devise_for :admins
  # devise_for :admins, controllers: {
  #   sessions: "admins/sessions",
  #   passwords: "admins/passwords"
  # }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    resources :teachers, only:[:index, :show]
    get '/about' => 'homes#about', as: 'about'
    get '/outline' => 'homes#show', as: 'outline'
    get '/social' =>'homes#social', as: 'social'
    get '/support' => 'homes#support', as: 'support'
    get '/classes' => 'homes#classes', as: 'classes'
    get '/privacy' => 'homes#privacy', as: 'privacy'
    resources :contacts, only: [:new, :create]
    resources :medias, only: [:index]
  end

  namespace :admin do
    # resources :contacts, only: [:index, :show]
    resources :medias,only: [:index,:edit,:update,:create,:destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, 
  # :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :name_kana, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :email, presence: true
  validates :phone, presence: true
end

app/models/media_post.rb
class MediaPost < ApplicationRecord
  validates :date_public, presence: true

  enum genre: {
    tv: 0,
    newspaper: 1,
    magazine: 2,
    web: 3,
    youtube: 4,
    other: 5
  }
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @contacts = Contact.page(params[:page]).per(10).order("created_at "+ sort_direction)
  end

  def show
    @contact = Contact.find(params[:id])
  end

  private
  def sort_direction
    # If params[:direction] is nil, set sort_direction to "desc" by default
    %W[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/controllers/admin/medias_controller.rb
class Admin::MediasController < ApplicationController
  before_action :authenticate_admin!
  def index
    @medias = MediaPost.page(params[:page]).per(10).order("date_public "+ sort_direction)
    @media = MediaPost.new
  end

  def edit
    @media = MediaPost.find(params[:id])
  end

  def create
    @media = MediaPost.new(media_post_params)
    if @media.save
      redirect_to admin_medias_path
    else
      @medias = MediaPost.page(params[:page]).per(10).order("date_public "+ sort_direction)
      render :index
    end
  end

  def update
    @media = MediaPost.find(params[:id])
    if @media.update(media_post_params)
      redirect_to admin_medias_path
    else
      render :edit
    end
  end

  def destroy
    @media = MediaPost.find(params[:id])
    @media.destroy
    redirect_to admin_medias_path
  end
  # 入力内容に誤りがあった場合、
  # 入力内容を保持したまま前のページに戻るのが当たり前になっているかと思いますが、
  # backアクションを定義することで可能となります。
  def back
    @media = MediaPost.new(contact_params)
    render :new
  end

  private
  def sort_direction
    # If params[:direction] is nil, set sort_direction to "desc" by default
    %W[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def media_post_params
    params.require(:media_post).permit(:title, :url,:date_public,:genre)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    # byebug
    case resource
      when Admin
        admin_medias_path
    end
  end

  def after_sign_in_path_for(resource)
    # byebug
    case resource
      when Admin
        admin_medias_path
    end
  end

  def configure_permitted_parameters
  end
end

app/helpers/admin/contact_helper.rb
module Admin::ContactHelper
  def sort_asc(column_to_be_sorted)
    link_to "▲", {:column => column_to_be_sorted, :direction => "asc"}
  end

  def sort_desc(column_to_be_sorted)
    link_to "▼", {:column => column_to_be_sorted, :direction => "desc"}
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/medias_helper.rb
module Admin::MediasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/contacts/index.html.erb
<%= render "admins/shared/header" %>
<p id="notice"><%= notice %></p>
<div class="toppage" style="height: 800px;">
  <div class="text-center mt-3">
    <h1 class="text-center undertitle">お問い合わせ一覧</h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <div class="mx-5 mb-4">
          <%= link_to "管理者トップへ戻る", admin_contacts_path, class: "btn btn-info" %>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>id</th>
              <th>問い合わせ日<%= sort_asc("created_at") %><%= sort_desc("created_at") %></th>
              <th>件名</th>
              <th>名前</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @contacts.each do |contact| %>
            <tr>
              <td><%= contact.id %></td>
              <td><%= contact.created_at.strftime("20%-y-%-m-%-d %-H:%-M") %></td>
              <td><%= contact.title %></td>
              <td><%= contact.name %></td>
              <td><%= link_to "詳細", admin_contact_path(contact), class: "btn btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @contacts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/contacts/show.html.erb
<%= render "admins/shared/header" %>
<%= link_to "一覧へ戻る", admin_contacts_path, class: "btn btn-info mx-5 mt-5" %>
<div class="text-center mt-4">
  <h1 class="text-center undertitle">問い合わせ内容</h1>
</div>
<div class="container">
  <div class="row">
    <table class="table col-md-3">
      <tr>
        <td>投稿日</td>
        <td><%= @contact.created_at.strftime("20%-y-%-m-%-d %-H:%-M") %></td>
      </tr>
      <tr>
        <td>お名前</td>
        <td><%= @contact.name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @contact.name_kana %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @contact.email %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @contact.phone %></td>
      </tr>
      <tr>
        <td>件名</td>
        <td><%= @contact.title %></td>
      </tr>
    </table>
    <div class="col-md-6 offset-md-1">
      <h5>本文</h5>
      <%= @contact.content %>
    </div>
  </div>
</div>

app/views/admin/medias/edit.html.erb
<%= render "admins/shared/header" %>
<p id="notice"><%= notice %></p>
<div class="toppage" style="height: 800px;">
  <div class="text-center mt-3">
    <h1 class="text-center undertitle">メディア掲載</h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <div class="mx-5 mb-4">
          <%= link_to "管理者トップへ戻る", admin_medias_path, class: "btn btn-info" %>
        </div>
        <h4>編集</h4>
        <div class="mb-4">
          <%= form_with model: @media, url: admin_media_path(@media) do |f| %>
          <table>
            <thead>
              <tr>
                <th><%= f.label :掲載日 %></th>
                <th><%= f.label :媒体 %></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.date_field :date_public %></td>
                <td><%= f.select :genre, MediaPost.genres_i18n.invert %></td>
              </tr>
            </tbody>
          </table>
          <div class="">
            <%= f.label :タイトル %><br />
            <%= f.text_field :title %>
          </div>
          <div class="field">
            <%= f.label :記事のURL %><br />
            <%= f.text_field :url %>
          </div>
          <div class="field mt-3">
            <%= f.submit "更新", class: "btn btn-success" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/medias/index.html.erb
<%= render "admins/shared/header" %>
<p id="notice"><%= notice %></p>
<div class="toppage">
  <div class="text-center mt-3">
    <h1 class="text-center undertitle">メディア掲載</h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <div class="mx-5 mb-4">
          <%= link_to "管理者トップへ戻る", admin_medias_path, class: "btn btn-info" %>
        </div>
        <h4>新規登録</h4>
        <div class="mb-4">
          <%= form_with model: @media, url: admin_medias_path do |f| %>
          <table>
            <thead>
              <tr>
                <th><%= f.label :掲載日 %></th>
                <th><%= f.label :媒体 %></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.date_field :date_public %></td>
                <td><%= f.select :genre, MediaPost.genres_i18n.invert %></td>
              </tr>
            </tbody>
          </table>
          <div class="">
            <%= f.label :タイトル %><br />
            <%= f.text_field :title %>
          </div>
          <div class="field">
            <%= f.label :記事のURL %><br />
            <%= f.text_field :url %>
          </div>
          <div class="field mt-3">
            <%= f.submit "新規登録", class: "btn btn-success" %>
          </div>
          <% end %>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>掲載日<%= sort_asc("date_public") %><%= sort_desc("date_public") %></th>
              <th>媒体</th>
              <th>タイトル</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @medias.each do |media| %>
            <tr>
              <td><%= link_to media.date_public.strftime("20%-y/%-m/%-d"),admin_media_path(media) %></td>
              <td><%= media.genre_i18n %></td>
              <td>
                <% if media.url.present? %>
                  <%= link_to media.title, media.url, target: :_blank, rel: "noopener noreferrer" %>
                <% else %>
                  <%= media.title %>
                <% end %>
              </td>
              <td><%= link_to "編集", edit_admin_media_path(media), class: "btn btn-info" %></td>
              <td><%= link_to "削除", admin_media_path(media), method: :delete, class: "btn btn-danger" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @medias %>
      </div>
    </div>
  </div>
</div>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "サインアップ", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れでしょうか?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_header.html.erb
<header class="shadow-sm sticky-top bg-white">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><div class="logo"></div></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "メディア掲載", admin_medias_path, class: 'nav-link text-dark' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to '管理者ログイン', new_admin_session_path, class: 'nav-link text-dark' %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name), class: "btn btn-success my-3" %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "新規登録", new_registration_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れでしょうか?", new_password_path(resource_name),class: "btn btn-info" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white pt-5 pb-4">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-3 mt-3">
        <%= link_to root_path do %>
        <%#= image_tag('logo.png') %>
        <div class="logo-footer"></div>
        <% end %>
      </div>
      <div class="col-md-3">
        <h5 class="text-white mt-2 mb-3">私たちについて</h5>
        <ul class="p-0 list-unstyled">
          <li><%= link_to "BORDER FREEとは", about_path, class: "text-white" %></li>
          <li><%= link_to "サービス紹介", classes_path, class: "text-white" %></li>
          <li><%= link_to "メディア掲載", medias_path, class: "text-white" %></li>
          <li><a href="https://note.com/border_free2021" target="_blank" rel="noopener noreferrer" class="text-white">ブログ</a></li>
          <li><%= link_to "団体概要", outline_path, class: "text-white" %></li>
        </ul>
      </div>
      <div class="col-md-3">
        <h5 class="text-white mt-2 mb-3">サポート</h5>
        <ul class="p-0 list-unstyled">
          <li><%= link_to "ご寄付・ボランティア", support_path, class: "text-white" %></li>
          <li><%= link_to "協賛企業・協賛団体", social_path, class: "text-white" %></li>
          <!--<li><%#= link_to "お問い合わせ", new_contact_path, class: "text-white" %></li>-->
          <li><a href="https://docs.google.com/forms/d/e/1FAIpQLScho7UETS3AAK3ScHctdH-NamXxy_3c3t7gVZbrWa8b-RSj0w/viewform" target="_blank" rel="noopener noreferrer" class="text-white">お問い合わせ</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <h5 class="text-white mt-2 mb-3">SNS</h5>
        <ul class="follow-me d-flex">
          <li>
            <a href="https://twitter.com/borderfree2021" target="_blank" rel="noopener noreferrer" class="btn-social-long-twitter">
              <i class="fa-brands fa-x-twitter"></i>
            </a>
          </li>
          <li class="mx-3">
            <a href="https://www.instagram.com/borderfree__official/" target="_blank" rel="noopener noreferrer" class="btn-social-icon-instagram">
              <span class="btn-social-icon-instagram__square"><i class="fab fa-instagram"></i></span>
            </a>
          </li>
          <!--<li><a href="https://www.instagram.com/border_free2021/"></a></li>-->
        </ul>
      </div>
    </div>
  </div>
  <div class="text-white text-center">
    <%= link_to '個人情報保護方針', 'pdf/privacy_ver3.pdf', target: '_blank', class: "text-white" %>
    <%#= link_to 'プライバシーポリシー', privacy_path(format: :pdf), target: '_blank', class: "text-white" %>
  </div>
  <div class="text-white text-center">
    Copyright © 特定非営利活動法人BORDER FREE　　　All rights reserved.
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="top"></div>
<header class="shadow-sm sticky-top bg-secondary">
  <nav class="navbar navbar-expand-lg navbar-light navbar-fixed-top">
    <div class="container">
      <%= link_to  root_path do %>
      <div class="d-flex">
        <!--<img src="assets/logo.jpg" alt="BORDER FREE", width="50">-->
        <div class="logo"></div>
        <h6 class="text-white pt-2 ml-3">特定非営利活動法人<br>BORDER FREE</h6>
        <%#= image_tag('logo.png') %>
      </div>
      <% end %>
      <!--<a class="navbar-brand p-3" href="/"></a>-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <li class="nav-item"><%= link_to 'ホーム', root_path,class: 'nav-link text-white' %></li>
        <li class="nav-item"><%= link_to '私たちについて', about_path,class: 'nav-link text-white' %></li>
        <li class="nav-item"><%= link_to "サービス紹介", classes_path, class: 'nav-link text-white' %></li>
        <li class="nav-item"><%= link_to "メディア掲載", medias_path, class: 'nav-link text-white' %></li>
        <li class="nav-item"><a href="https://note.com/border_free2021" target="_blank" rel="noopener noreferrer" class="nav-link text-white">ブログ</a></li>
        <li class="nav-item"><%= link_to '寄付をする', support_path,class: 'nav-link text-white' %></li>
        <!--<li class="nav-item"><a href="https://congrant.com/project/borderfree/9791" target="_blank" rel="noopener noreferrer" class="btn_25 nav-link"><span>寄付をする</span></a></li>-->
        <!--<li class="nav-item"><%#= link_to "お問い合わせ", new_contact_path, class: 'nav-link text-white' %></li>-->
        <li class="nav-item"><a href="https://docs.google.com/forms/d/e/1FAIpQLScho7UETS3AAK3ScHctdH-NamXxy_3c3t7gVZbrWa8b-RSj0w/viewform" target="_blank" rel="noopener noreferrer" class="nav-link text-white">お問い合わせ</a></li>
        <% if admin_signed_in? %>
        <li class="nav-item"><%= link_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %></li>
        <% else %>
        <!--<li class="nav-item">-->
          <%#= link_to '管理者ログイン', new_admin_session_path, class: 'nav-link text-white' %>
        <!--</li>-->
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_question.html.erb
<div class="row margin-top">
  <div class="cta_btn03 col-md-6 offset-md-4">
  <%#= link_to new_contact_path do %>
  <a href="https://docs.google.com/forms/d/e/1FAIpQLScho7UETS3AAK3ScHctdH-NamXxy_3c3t7gVZbrWa8b-RSj0w/viewform" target="_blank" rel="noopener noreferrer" class="nav-link text-white">
    <span class="cta_btn03-copy">お気軽にお問い合わせください！</span>
    <div class="text-white">お問い合わせはこちら</div>
  </a>
  <%# end %>
  </div>
</div>

app/views/layouts/_supporter.html.erb
<div class="row mt-5">
  <div class="col-md-8 offset-md-2">
    <div class="box72">
      <div class="box-title">名前一覧　(順不同)</div>
      <ul>
        <li>ビッツ有限会社 村上幸雄様</li>
        <li>末吉陽一様</li>
        <li>大山 紘平様</li>
        <li>斎藤拓也様</li>
        <li>大場実様</li>
        <li>ひでさん様</li>
        <li>金子利佳様</li>
        <li>五十嵐崇様</li>
        <li>オーガナイジングサービス 岩崎 美乃様</li>
        <li>KAZUYO KAWAMURA様</li>
        <li>原島陽子様</li>
        <li>小笠原弘実様</li>
        <li>まるぞう様</li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_supporters.html.erb
<div class="row text-center">
  <div class="ml-5">
    <div class="greenade supporters-logo"></div>
    <p class="display-none">グリナード永山 様</p>
  </div>
  <div class="ml-5">
    <div class="kelu supporters-logo"></div>
    <p class="display-none">ケル株式会社 様</p>
  </div>
  <div class="ml-5">
    <div class="tama supporters-logo"></div>
    <p class="display-none">多摩市 様</p>
  </div>
  <div class="ml-5">
    <div class="atl supporters-logo"></div>
    <p class="display-none">株式会社エーティーエル<br>システムズ 様</p>
  </div>
  <div class="ml-5">
    <div class="tamakyo supporters-logo"></div>
    <p class="display-none">多摩市社会福祉<br>協議会 様</p>
  </div>
</div>
<div class="row mt-5">
  <div class="col-md-8 offset-md-2">
    <div class="box72">
      <div class="box-title">協賛企業・協賛団体　(順不同)</div>
      <ul>
        <li>グリナード永山 様</li>
        <li>ケル株式会社 様</li>
        <li>多摩市 様</li>
        <li>株式会社エーティーエルシステムズ 様</li>
        <li>多摩市社会福祉協議会 様</li>
        <li>東京海上日動システムズ株式会社 様</li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NPO法人 BORDER FREE 学習支援</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/e5b157651e.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
    <script src="https://cdn.tiny.cloud/1/bau63o8ymi3opbmfa577ykcie0qc3sf62sju9mb3uhclq5l8/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
  </head>

  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-QT9WNV0F2J"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-QT9WNV0F2J');
  </script>

  <body>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/teacher/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>